// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:260126413769:web:ddd110d9bd6d0068538e18',
    messagingSenderId: '260126413769',
    projectId: 'kigali-d887a',
    authDomain: 'kigali-d887a.firebaseapp.com',
    storageBucket: 'kigali-d887a.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: '1:260126413769:android:3bc9930f8348bb91538e18',
    messagingSenderId: '260126413769',
    projectId: 'kigali-d887a',
    storageBucket: 'kigali-d887a.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:260126413769:ios:8d98982d93ffbd39538e18',
    messagingSenderId: '260126413769',
    projectId: 'kigali-d887a',
    storageBucket: 'kigali-d887a.firebasestorage.app',
    iosBundleId: 'com.example.kigali',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY']!,
    appId: '1:260126413769:ios:8d98982d93ffbd39538e18',
    messagingSenderId: '260126413769',
    projectId: 'kigali-d887a',
    storageBucket: 'kigali-d887a.firebasestorage.app',
    iosBundleId: 'com.example.kigali',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY']!,
    appId: '1:260126413769:web:c718a2a659c3cd86538e18',
    messagingSenderId: '260126413769',
    projectId: 'kigali-d887a',
    authDomain: 'kigali-d887a.firebaseapp.com',
    storageBucket: 'kigali-d887a.firebasestorage.app',
  );
}
